### ISSUE TITLE
bimohxh，你好

### ISSUE THREAD

**Issue by dabing1022** [bimohxh/aweb#1]
bimohxh，你好，实在不知道怎么联系到你，特来这里开了个issue，见谅。

我再RubyChina上见到你曾经遇到过[https://ruby-china.org/topics/26378](https://ruby-china.org/topics/26378)微信accessToken接口超时的问题，请问当时是什么原因引起呢？我现在也遇到了类似的问题。

非常感谢，也非常抱歉在这开辟一个无关的issue。

**Comment by bimohxh** [comment]
实在不好意思，忘了当初是什么原因造成的
